apiVersion: v1
kind: Service
metadata:
  name: {{.Values.svcName}}
  labels:
    app: {{.Values.appName}}
spec:
  type: {{.Values.service.type}}
  ports:
  - port: {{.Values.service.ports.port}}
    targetPort: 3000
  selector:
    app: {{.Values.appName}}