apiVersion: v1
kind: Service
metadata:
  name: mosquitto-grafana-lb
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-name: "ismimi.iottrial.com"
    service.beta.kubernetes.io/do-loadbalancer-protocol: "tcp"
    service.beta.kubernetes.io/do-loadbalancer-enable-backend-keepalive: "true"
    service.beta.kubernetes.io/do-loadbalancer-backend-keepalive-timeout: "3600"
    # service.beta.kubernetes.io/do-loadbalancer-health-check-protocol: "tcp"
    # service.beta.kubernetes.io/do-loadbalancer-health-check-port: "1883"
spec:
  selector:
    app-group: mosquitto-grafana
  ports:
    - name: mosquitto-port
      protocol: TCP
      port: 1883
      targetPort: 1883
    - name: grafana-port
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
  # externalTrafficPolicy: Cluster  # Changed from Local to Cluster