apiVersion: v1
kind: Service
metadata:
  name: mosquitto-service
  labels:
    app: mosquitto
spec:
  type: LoadBalancer  # Expose the service externally
  selector:
    app: mosquitto  # This must match the labels in your Mosquitto deployment
  ports:
    - protocol: TCP
      port: 1883  # MQTT default port
      targetPort: 1883  # Port where Mosquitto is running in the container
      nodePort: 31883  # Optional: Manually specify a NodePort (range: 30000-32767)