apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
data:
  mosquitto.conf: |
    # Mosquitto configuration
    persistence true
    persistence_location /mosquitto/data
    log_dest stdout

    allow_anonymous false

    # Use the password file from ConfigMap
    password_file /mosquitto/auth/mosquitto.passwd
  
    listener 1883 0.0.0.0

    # Hardcoded credentials
   # password ismama:$7$101$7cYVXDVU2/R7RiRG$qQgGXA0av5BeFxpUehfDlulOSrKshaf1MWN/eYqjtiNJAD+EVBrNwwSJ4WBD515DdZ/PjpU6cZisYlzssht6w==
