apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.cfgName}}
data:
  telegraf.conf: |
    [agent]
      interval = {{ .Values.agent.interval | quote }}
      flush_interval = {{ .Values.agent.flushInterval | quote }}
      debug = {{ .Values.agent.debug }}
      quiet = {{ .Values.agent.quiet }}
    [[inputs.mqtt_consumer]]
      servers = {{ .Values.mqtt.servers | toJson }}
      topics = {{ .Values.mqtt.topics | toJson }}
      data_format = {{ .Values.mqtt.dataFormat | quote }}
      username = "${MQTT_USERNAME}"  # Replace with your Mosquitto username ismimi 
      password = "${MQTT_PASSWORD}"  # Replace with your Mosquitto password 12345678
      [[inputs.mqtt_consumer.json_v2]]
        measurement_name = {{ .Values.mqtt.measurementName | quote }}
        {{- range .Values.mqtt.fields }}
        [[inputs.mqtt_consumer.json_v2.field]]
          path = {{ .path | quote }}
          type = {{ .type | quote }}
        {{- end }}
    
    [[outputs.file]]
      files = {{ .Values.outputs.file.files | toJson }}
      data_format = {{ .Values.outputs.file.dataFormat | quote }}

    [[outputs.influxdb_v2]]
      urls = {{ .Values.outputs.influxdb.urls | toJson }}
      token = {{ .Values.outputs.influxdb.token | quote }}
      organization = {{ .Values.outputs.influxdb.organization | quote }}
      bucket = {{ .Values.outputs.influxdb.bucket | quote }}