apiVersion: v1
kind: PersistentVolume
metadata:
  name: mosquitto-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mosquitto-storage
  hostPath:
    path: "/mnt/data/mosquitto"  # Inside Minikube VM (mapped to ~/mosquitto-data)

