apiVersion: v1
kind: Secret
metadata:
  name: mosquitto-secret-file
type: Opaque
data:
  mosquitto.passwd: aXNtaW1pOiQ3JDEwMSRXcTNRdk53OWl5cm85RzdaJGFiYlFlSkN3V3JmK2lIWkhEcThKeEwzczJXMDYreWFxSmNReldXMXEvM2cvdGxKbDJZUnh6ZHQxbjEvMGRFWFFZTm0zZ0wvN2c3MGRZbmNaa28yVU5nPT0K