apiVersion: v1
kind: Service
metadata:
  name: {{.Values.svcName}}
  labels:
    app: {{.Values.appName}}
spec:
  type: {{.Values.service.type}}  # Expose the service externally
  selector:
    app: {{.Values.appName}}  # This must match the labels in your Mosquitto deployment
  ports:
    - name: mqtt-internal
      protocol: TCP
      port: {{.Values.service.ports.port}}  # MQTT default port
      targetPort: {{.Values.service.ports.port}}  # Port where Mosquitto is running in the container
      #nodePort: {{.Values.service.ports.nodePort}}  # Optional: Manually specify a NodePort (range: 30000-32767)